### ISSUE TITLE
New messages do not appear on receiver screen without refresh

### ISSUE THREAD

**Issue by kirovelikov** [RTippin/messenger#25]
Hello.

I want to congratulate you for the great job. I managed to make it work with my Laravel project, but for some reason new messages are not showing on receiver screen until page is refreshed. I can see the icon when the other user is typing but not the message itself.

**Comment by RTippin** [comment]
Thanks! 

Can you share any more information? It sounds like a possible UI issue. Are there any errors in your browsers console?

**Comment by kirovelikov** [comment]
Hello. No errors in the console. When a message is sent from one window, after a minute or two navbar messenger icon shows there is an unread message. About 5 minutes later the message is shown in Conversations tab as last conversation message but never appears in chat window (or at least I have never waited long enough before hitting F5)

**Comment by RTippin** [comment]
Yea the threads list in the UI updates itself every 5 minutes, and there is a status heartbeat every two minutes. 

What solution are you using for websockets?

One other thing to check, are your user models using UUID or auto-incrementing primary keys? Be sure it matches the `messenger.provider_uuids` config flag.

**Comment by kirovelikov** [comment]
I made it work. Sorry for wasting your time. You can delete the issue

**Comment by RTippin** [comment]
All good, mind sharing what the issue was in case someone else encounters it? 🙂

**Comment by kirovelikov** [comment]
My pusher configuration in broadcasting.php was not as given in messenger-ui  installation notes

        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'useTLS' => false,
            ],
        ], 

Thanks again for your efforts
