### ISSUE TITLE
Used just for api part

### ISSUE THREAD

**Issue by radudiaconu0** [RTippin/messenger#4]
It can be used just for api too? i mean without blade frontend part on sa separate spa(like nuxtjs for example).

**Comment by RTippin** [comment]
It sure can. You can even disable the web routes in the routing part of my
config. All images and documents have both web and api routes, and
everything else is REST anyway.

**Comment by radudiaconu0** [comment]
cool. alsot i would be cool if i can use this with laravel websockets package

**Comment by RTippin** [comment]
You can, only my optional frontend right now required socketio js library. Backend wise it uses whatever broadcast driver your laravel app is set on. Don't confuse my packages "broadcast driver" with laravels, as mine is simply how I generate private/presence channel names.

**Comment by radudiaconu0** [comment]
so this package supports one to one and one to many chat/videochat? you saved me from a a lot of unnecesary work :)))

**Comment by radudiaconu0** [comment]
do you have disocrd or something? i want to discuss more with you ;))

**Comment by radudiaconu0** [comment]
the package is pretty complicated and i need some help @RTippin

**Comment by RTippin** [comment]
Give me a bit, working with a client right now. Send me an email to start a thread, we can share details / discord there. richard.tippin@gmail.com
