### ISSUE TITLE
How to search in all users? And add participants in a group?

### ISSUE THREAD

**Issue by arifbsl** [RTippin/messenger#40]
# 1. How can a user search all users (including new fresh users) for conversations?
# In the users table
![](https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/f1e66ca6-1ba6-42f8-a5df-3dee759a273e.gif?ClientID=vimeo-core-prod&Date=1647025544&Signature=907e1d3ba3ad1792b7d6ceb45fbbe77907f08cb5)

# Getting only logged in user
## I want to get search results from all new users. Logged in or not.
![](https://videoapi-muybridge.vimeocdn.com/animated-thumbnails/image/c01476d2-ef81-4fbe-bf3e-8764970259b9.gif?ClientID=vimeo-core-prod&Date=1647025588&Signature=afa6d23901687b802d2722d122c3b3597ccc923c)

# in user model 
## Implements
```php
class User extends Authenticatable implements MessengerProvider
```
## Using traite
```php
use Messageable;
```
## Setting method
```php
   public static function getProviderSettings(): array
    {
        return [
            'alias' => 'user',
            'searchable' => true,
            'friendable' => true,
            'devices' => true,
            'default_avatar' => public_path('vendor/messenger/images/users.png'),
            'cant_message_first' => [],
            'cant_search' => [],
            'cant_friend' => [],
        ];
    }
```

## Searchable method
```php
   public static function getProviderSearchableBuilder(
        Builder $query,
        string $search,
        array $searchItems
    ) {
        $query->where(function (Builder $query) use ($searchItems) {
            foreach ($searchItems as $item) {
                $query->orWhere('name', 'LIKE', "%{$item}%");
            }
        })->orWhere('email', '=', $search);
    }
```

# 2. How can users add participants in a group without being friends?
I am using `BIGINT` id in the users table

**Comment by RTippin** [comment]
> 1. How can a user search all users (including new fresh users) for conversations?

The search feature uses the `messengers` table, which requires you to implement creating my `Messenger` model upon your new user creation. Please see my docs on the matter for how/when to make/attach messenger models to your providers.
> [Messenger Model](https://github.com/RTippin/messenger/blob/ae23a35627767ce504c9e4a1b41186d23f31bb60/docs/Installation.md#messenger-model)

---

> 2. How can users add participants in a group without being friends?

Firstly, you can generate group thread invites and send the invite to anyone you want to join the group (similar to discord invites). 

Second, to be able to add non-friends to the group directly, you can disable the friendship checks via the config `MESSENGER_VERIFY_GROUP_THREAD_FRIENDSHIP`.
> [Friendship Checks](https://github.com/RTippin/messenger/blob/ae23a35627767ce504c9e4a1b41186d23f31bb60/docs/Configuration.md#thread-verifications--friendship-checks)

The one caveat when disabling group thread friendship checks is that my optional `messenger-ui` UI, you can only "view" friends to add via the popup modal. If you want to be able to view all users and pick who to add to a group, you will have to build that UI / API integration yourself, as the current included endpoint ( [Add participants](https://tippindev.com/api-explorer/routes/api.messenger.threads.add.participants) ) filters out current group participants against your friends list. However, if you build the UI yourself, the ( [Store Participants](https://tippindev.com/api-explorer/routes/api.messenger.threads.participants.store) ) endpoint will accept any valid provider alias/ID combo.

Messenger v2 is still a ways out, but I am planning to give more control over these options, but that also includes me making a brand new optional UI (will be in react).

**Comment by Sandbird** [comment]
For anyone interested, this is how I did it.

By default, participants are returned from the following method:
\rtippin\messenger\src\Brokers\FriendBroker.php
public function getProviderFriendsNotInThread(Thread $thread)

Create a new file at app/Services/CustomFriendBroker.php, in order to override this method.

```
<?php

namespace App\Services;

use App\Models\User;
use RTippin\Messenger\Models\Friend;
use RTippin\Messenger\Brokers\FriendBroker;
use RTippin\Messenger\Messenger;

class CustomFriendBroker extends FriendBroker
{
    public function getProviderFriendsNotInThread($thread)
    {
        // My custom implementation
        $participants = $thread->participants()->get();

        return User::whereNotIn('id', $participants->where('owner_type', '=', User::class)->pluck('owner_id'))
            ->get()
            ->map(function ($user) {
                $friend = new Friend;
                $friend->id = $user->id; // Critical - use real ID
                $friend->owner_id = auth()->id(); // You own these records
                $friend->owner_type = \App\Models\User::class;
                $friend->party_id = $user->id;
                $friend->party_type = \App\Models\User::class;
                $friend->created_at = now();
                $friend->updated_at = now();
                $friend->setRelation('party', $user);
                $friend->setRelation('owner', auth()->user()); // Set you as owner

                return $friend;
            });
    }
}
```

Now, open App\Providers\AppServiceProvider.php and modify the register() method to extend the original FriendDriver. Place this at the bottom.

```
public function register()
{
    // CustomFriendBroker
    $this->app->extend(
        \RTippin\Messenger\Contracts\FriendDriver::class,
        function ($originalService, $app) {
            // Pass the Messenger instance
            return new \App\Services\CustomFriendBroker(
                $app->make(\RTippin\Messenger\Messenger::class)
            );
        }
    );
}
```

Now, getProviderFriendsNotInThread will use your custom logic to return all users
```
php artisan config:clear
php artisan cache:clear
```
