### ISSUE TITLE
API explorer at https://tippindev.com/api-explorer: Page not loading

### ISSUE THREAD

**Issue by craftisan** [RTippin/messenger#42]
Please check the app you have linked in the documentation. The API explorer is not opening up, in fact the entire site seems to be down.

It'd be great if I could see the demo app in action along with the API documentation.

Cheers!

**Comment by RTippin** [comment]
My site is still working, have not seen any reported downtime. Firewall could be locking specific Geo-locations, so if you still see it down, you may need to try a VPN. Sorry for any inconveniences.
