### ISSUE TITLE
Not finding my existing users

### ISSUE THREAD

**Issue by enanwangai** [RTippin/messenger#48]
### Discussed in https://github.com/RTippin/messenger/discussions/47

<div type='discussions-op-text'>

<sup>Originally posted by **enanwangai** August 30, 2022</sup>
Hi, I need assistance I am pretty new t this package and I am unable to display or search the users from the messenger platform. What could be the issue? 
I already have users in this existing model... 
![image](https://user-images.githubusercontent.com/112321535/187380028-665cdf9c-d552-4f90-9f67-c5363afcfb69.png)
</div>

**Comment by RTippin** [comment]
Please see the following from the install docs, to attach the messenger model to existing records. The search functionality requires your providers to have their related messenger model already created, thus I provide the command to store the records for existing providers, while you'll want to store them yourself when you create new users/providers.

> https://github.com/RTippin/messenger/blob/1.x/docs/Installation.md#attaching-the-model-to-your-existing-records
