### ISSUE TITLE
Messenger (USer model) fields

### ISSUE THREAD

**Issue by vishalag991** [RTippin/messenger#51]
Thanks for this wonderful package. 

Currently package returns all fields of our 'User' model. This includes phone numbers etc also. How can we modify the 'Base' response object?

**Comment by RTippin** [comment]
Thanks! There is no easy way to completely overwrite my provider https://github.com/RTippin/messenger/blob/92cca2804e74b79319be6177083c728ca0244038/src/Http/Resources/ProviderResource.php#L71

However, if you set the `$hidden` property on your model, those columns will not be used when your model is serialized, including from within my package.
> https://laravel.com/docs/9.x/eloquent-serialization#hiding-attributes-from-json

**Comment by vishalag991** [comment]
Thanks for prompt response. Closing this issue.
