### ISSUE TITLE
Unable to install it on Laravel 9 ??? Help me to fix it

### ISSUE THREAD

**Issue by chegmarco1989** [RTippin/messenger#63]
Hello.

We got `Your requirements could not be resolved to an installable set of packages.` error as you can see in the following error when we are trying install this package on our Laravel 9 existing project. We can not upgrade that Laravel 9 to Lavarel 10 because the project already uses several projects (packages) that require Laravel 9.

![image](https://github.com/RTippin/messenger/assets/51763985/25639d4e-07fc-4f5e-b938-2eab4ffbcfd2)

So, @RTippin , is there any way to install it on Laravel 9 please ???

**Comment by RTippin** [comment]
I've listed the messenger release versions for each laravel version in my readme:

https://github.com/RTippin/messenger/blob/83bb92d1e7ec1b87838179fe80cbac6658b37c0d/README.md#prerequisites

So for laravel 9, you need to install `^1.21.0`

```bash
composer require rtippin/messenger:1.21.0
```

**Comment by chegmarco1989** [comment]
Thanks
