### ISSUE TITLE
heartbeat problem

### ISSUE THREAD

**Issue by michalevk** [RTippin/messenger#70]
Hey, when will I enable MESSENGER ONLINE STATUS ENABLED in the .env
I have such errors

![image](https://github.com/RTippin/messenger/assets/144418368/6ca08b87-3a89-4758-8540-e468ed2b1553)

**Comment by RTippin** [comment]
@michalevk That's a backend error (see the server error 500 in console). You'll need to view your servers error/laravel log to see what's causing it.

**Comment by michalevk** [comment]
in fact, it already works. But I have another problem because I use websockets, I think I have configured the front correctly, everything is live but the messages are not arriving. Do you know what might be going on?
![image](https://github.com/RTippin/messenger/assets/144418368/380abf3c-b66d-4b24-8d0f-15a5d8cd36af)

**Comment by michalevk** [comment]
> in fact, it already works. But I have another problem because I use websockets, I think I have configured the front correctly, everything is live but the messages are not arriving. Do you know what might be going on? ![image](https://user-images.githubusercontent.com/144418368/278237884-380abf3c-b66d-4b24-8d0f-15a5d8cd36af.png)

I noticed a problem with e-mail that only appears when we connect our SSL certificate. when I turn it off, the messages come normally. The strange thing is that websockets works on SSL and they see some of the user's interactions live
