### ISSUE TITLE
Intervention/imagecache abandoned

### ISSUE THREAD

**Issue by fpolli** [RTippin/messenger#74]
When installing with composer, received this message:

Package intervention/imagecache is abandoned, you should avoid using it. No replacement was suggested.

**Comment by fpolli** [comment]
I see from perusing recent changes that this issue is related to me adding to a laravel 9 project.

**Comment by RTippin** [comment]
@fpolli The warning would only happen on fresh installs, but I am aware of it. Once laravel 11 releases and I have a chance to ensure this package is updated, I will be looking to replace or remove the usage of the imagecache package.

**Comment by RTippin** [comment]
This package has simply been removed as a dependency.
