### ISSUE TITLE
Laravel 11 support?

### ISSUE THREAD

**Issue by mustafa-online** [RTippin/messenger#75]
Any plans to support laravel 11 ?

**Comment by RTippin** [comment]
@mustafa-online I will see what I can do this coming weekend. The main challenge will be updating my UI addon as it requires much more work, just to be able to rebuild the JS assets.

**Comment by RTippin** [comment]
@mustafa-online I have tagged the backend packages to work with L11. Let me know if you experience any issues.

**Comment by mustafa-online** [comment]
@RTippin thanks a lot 👏
I will test it soon.
