### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by ThcDelux3** [RTippin/messenger#8]
I know this is the issue tab. But WOW great project! Keep going. If you need help with a Vue version I might can help to migrate this project to InertiaJs.

**Comment by RTippin** [comment]
Thank you for the kind words! As for frontend plans, I currently have one guy working on react and another on Vue, but I am open for any and all suggestions/contributions! More than likely, I will detach any frontend stacks from this base package before v1 (keeping it purely the core/api) and have separate repos for the end user to install a UI of their choice, or make their own. If you happen to make your own UI using my backend, I will happily link to it in my docs for future users to have choices of pre-made solutions to pick from.
